<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AAP_TUUA.Dao\AAP_TUUA.Dao.csproj" />
    <ProjectReference Include="..\AAP_TUUA.Entidades\AAP_TUUA.Entidades.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
